### ISSUE TITLE
Danger Swift 1.5.3: error: missing required module 'DangerShellExecutor'

### ISSUE THREAD

**Issue by erikstrottmann** [danger/swift#228]
Since the new Danger Swift 1.5.3 release today, our Danger jobs are failing on CI. We did not experience this yesterday using Danger Swift 1.5.2.

This is the error message we get:
```
/var/folders/yy/d215g62s727f4w2137t9jl2m0000gn/T/_tmp_dangerfile.swift:2:8: error: missing required module 'DangerShellExecutor'
i
mport Danger
       ^

ERROR: Dangerfile eval failed at Dangerfile.swift
ERROR: Could not get the results JSON file at /var/folders/yy/d215g62s727f4w2137t9jl2m0000gn/T/danger-response.json

Failing the build, there is 1 fail.
Feedback: https://github.com/clutter/clutter-ios-wms/pull/1298#issuecomment-484729025
Exited with code 1
```

We’re using Xcode 10.1 on CircleCI. The relevant parts of our `.circleci/config.yml`:
```yml
    steps:
      - checkout
      - run: brew tap danger/tap
      - run: brew install danger/tap/danger-swift
      - run: brew install swiftlint
      - run:
          name: Danger
          command: danger-swift ci
```
