### ISSUE TITLE
Danger doesn't recognise that it's a CI (Drone)

### ISSUE THREAD

**Issue by iussefatt** [danger/swift#263]
I can't get `ci` command to run in my drone pipeline:

This is my `drone.yml`

```yml
danger:
    image: appleboy/drone-ssh:1.4.0
    username: ios
    secrets: [ danger_github_api_token ]
    script:
      - PATH=$PATH:/usr/local/bin
      - danger-swift ci || exit
    trigger:
      event:
         - pull_request
```

and the output is: 
`Could not find a CI source for this run. Does Danger support this CI service?`

`DANGER_GITHUB_API_TOKEN` produces my correct token

Am I missing something?
