### ISSUE TITLE
Updating GitHub Action to latest build. 

### ISSUE THREAD

**Issue by alok-dks** [danger/swift#401]
It seems GitHub action is not in sync with what is latest here. 
Can you guys please update it?

**Comment by f-meloni** [comment]
Hi, 
do you mean the GitHub Package (https://github.com/orgs/danger/packages/container/package/danger-swift) or the Action itself?
Because the Package is updated, and for the action you can point any tag in the repo, so if you use 

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: danger/swift@3.7.1
        with:
            args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

You will get the latest released version
