### ISSUE TITLE
"Error deserializing SwiftLint JSON response" when using Xcode 13.4 on GitHub Actions

### ISSUE THREAD

**Issue by yonat-ateam** [danger/swift#522]
I have updated my swift package to `swift-tools-version:5.6`, and my GA workflow to use Xcode 13.4:

```yml
jobs:
  Lint:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: "/Applications/Xcode_13.4.app/Contents/Developer"
    ...
```

Now I get this error from Danger:

. | Fails
--- | ---
🚫  | Error deserializing SwiftLint JSON response (): dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Unable to parse empty data." UserInfo={NSDebugDescription=Unable to parse empty data.})))

My Dangerfile.swift is simple:

```swift
import Danger
let danger = Danger()
SwiftLint.lint(inline: true)
```

Any ideas how to fix?
